version: '3.8'

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                user: laravel
                uid: 1000
        container_name: laravel_app
        restart: unless-stopped
        tty: true
        working_dir: /var/www/html
        volumes:
            - ./:/var/www/html
        networks:
            - gsmpay_network

    webserver:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./docker/nginx:/etc/nginx/conf.d
        networks:
            - gsmpay_network
        depends_on:
            - app
            - db

    db:
        image: mysql:8.0
        container_name: mysql_db
        restart: unless-stopped
        tty: true
        ports:
            - "13306:3306"
        environment:
            MYSQL_DATABASE: gsmpay
            MYSQL_USER: gsmpay
            MYSQL_PASSWORD: gsmpay
            MYSQL_ROOT_PASSWORD: toor
        volumes:
            - dbdata:/var/lib/mysql
        networks:
            - gsmpay_network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        tty: true
        ports:
            - "8081:80"
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: secret
        networks:
            - gsmpay_network
        depends_on:
            - db

volumes:
    dbdata:
        driver: local

networks:
    gsmpay_network:
        driver: bridge
